apiVersion: v1
kind: Pod
metadata:
  name: microservice-libreria-pod
  labels:
    app: microservice-libreria
    type: microservice
spec:
  containers:
    - name: microservice-libreria-app
      image: deploysantiago/serviciosapilibreria:latest
      ports:
        - containerPort: 80
      env:
        - name: MongoDB__ConexionString
          value: mongodb://santiago:$Deploysantiago2022@mongo-service:27017
